events {}

http {
	# Include the file that maps file extensions to MIME types
	include /etc/nginx/mime.types;

	# Fallback MIME type used when NGINX cannot determine the file type
	default_type application/octet-stream;

	# Enable efficient file transfer for static files
	sendfile on;

	keepalive_timeout 65;

	server{
		listen 443 ssl;

		server_name jlima-so.42.fr;
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;
		ssl_protocols TLSv1.2 TLSv1.3;
		root /var/www/html;
		index index.php index.html index.htm;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php {
			# Include default FastCGI parameters required to pass the request correctly
			include fastcgi_params;

			# Forward PHP requests to the WordPress container running php-fpm on port 9000
			fastcgi_pass wordpress:9000;

			# Default PHP file to use when a directory is requested
			fastcgi_index index.php;

			# Tell php-fpm which PHP script file should be executed
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}

		location ~ /\.ht{
			deny all;
		}
	}
}
