[www]
; Define the user and group that will run PHP-FPM processes
; Usually www-data for web servers like NGINX
user = www-data
group = www-data

; Define the address and port where PHP-FPM listens for requests
; NGINX will send PHP requests to this port
listen = 9000

; Set ownership of the socket/listener (important for permissions)
listen.owner = www-data
listen.group = www-data

; Process manager type
; dynamic = adjusts number of processes based on load
pm = dynamic

pm.max_children = 5

pm.start_servers = 2

pm.min_spare_servers = 1

pm.max_spare_servers = 3

clear_env = no
